name: cohorts

channels:
    - defaults
    - conda-forge
 
dependencies:
    - python
    - bunch
    - seaborn
    - matplotlib
    - numpy
    - jupyterlab
    # Required to fix next tqdm issue:
    # Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls.
    - ipywidgets
    - tqdm
    - pip
    - pip:
 
