name: cohorts

channels:
    - defaults
    - conda-forge
 
dependencies:
    - python
    - matplotlib=3.7.3
    - numpy
    - missingno
    - jupyterlab
    - pip
    - pip:
        - seaborn
        - openpyxl
 
